"""Decision system constants and configurable weights.

All scoring weights and thresholds used in the aggregation pipeline.
Adjust these values based on evaluation results.
"""




RISK_SCORE_LOW = 1.0
RISK_SCORE_MINIMAL = 0.9
RISK_SCORE_MODERATE = 0.6
RISK_SCORE_MEDIUM = 0.55
RISK_SCORE_BALANCED = 0.55
RISK_SCORE_ELEVATED = 0.35
RISK_SCORE_HIGH = 0.15
RISK_SCORE_CRITICAL = 0.0
RISK_SCORE_DEFAULT = 0.45




DIRICHLET_PRIOR = 1.0
RELIABILITY_CONFIDENCE_WEIGHT = 0.8
CONFIDENCE_BONUS_WEIGHT = 0.2
MIN_LEAK = 0.05
LEAK_FACTOR = 0.25




RELIABILITY_BASE_FLOOR = 0.35
RELIABILITY_CONFIDENCE_FACTOR = 0.5
RELIABILITY_MIN = 0.1
RELIABILITY_MAX = 0.95


MELCHIOR_BASE_WEIGHT = 0.55
MELCHIOR_COVERAGE_WEIGHT = 0.45
MELCHIOR_COVERAGE_SCALE = 220.0


BALTHASAR_BASE_WEIGHT = 0.5
BALTHASAR_COVERAGE_WEIGHT = 0.5
BALTHASAR_COVERAGE_SCALE = 240.0


CASPER_BASE_WEIGHT = 0.45
CASPER_COVERAGE_WEIGHT = 0.3
CASPER_RISK_ALIGNMENT_WEIGHT = 0.25
CASPER_COVERAGE_SCALE = 200.0


FALLBACK_BASE_WEIGHT = 0.6
FALLBACK_COVERAGE_WEIGHT = 0.4
FALLBACK_COVERAGE_SCALE = 200.0




PERSONA_COUNT = 3.0


CONSENSUS_ANALYSIS_DEPTH_SCALE = 160.0
CONSENSUS_PLAN_DEPTH_SCALE = 160.0
CONSENSUS_MITIGATION_DEPTH_SCALE = 140.0


UNIFORM_PROBABILITY = 1.0 / 3.0


BASE_SAFETY_RISK_WEIGHT = 0.6
BASE_SAFETY_MITIGATION_WEIGHT = 0.4


EVIDENCE_DEPTH_WEIGHT = 0.5
EVIDENCE_CONFIDENCE_WEIGHT = 0.5


STRATEGY_DEPTH_WEIGHT = 0.5
STRATEGY_CONFIDENCE_WEIGHT = 0.5


APPROVE_PROB_BASE = 0.6
APPROVE_EVIDENCE_BONUS = 0.25
APPROVE_CONSENSUS_BONUS = 0.15
APPROVE_SAFETY_WEIGHT = 0.35
APPROVE_FUSED_CONF_WEIGHT = 0.2
APPROVE_RISK_PENALTY = 0.55
APPROVE_REJECT_PENALTY = 0.35


REJECT_PROB_BASE = 0.55
REJECT_RISK_BONUS = 0.25
REJECT_RISK_WEIGHT = 0.45
REJECT_UNSAFETY_WEIGHT = 0.3
REJECT_APPROVE_SAFETY_PENALTY = 0.4


REVISE_PROB_BASE = 0.5
REVISE_DISSENSUS_BONUS = 0.2
REVISE_EVIDENCE_GAP_WEIGHT = 0.3
REVISE_STRATEGY_GAP_WEIGHT = 0.3




SAFETY_APPROVE_THRESHOLD = 0.4
PROB_APPROVE_THRESHOLD = 0.4
SAFETY_REJECT_THRESHOLD = 0.6
PROB_REJECT_THRESHOLD = 0.35
DECISION_MARGIN_THRESHOLD = 0.18
LOW_CONFIDENCE_THRESHOLD = 0.4




HEURISTIC_WEIGHT = 0.5
MODEL_WEIGHT = 0.5
MODEL_OVERRIDE_MARGIN = 0.1


FALLBACK_PROB_APPROVE = 0.34
FALLBACK_PROB_REVISE = 0.33
FALLBACK_PROB_REJECT = 0.33


APPROVE_PROB_FLOOR = 0.75


FUSED_CONFIDENCE_OVERRIDE_THRESHOLD = 0.6
APPROVE_PROB_OVERRIDE_THRESHOLD = 0.35
